version: '2'
services:
    tidyup-app:
        image: tidyup
        external_links:
            - tidyup-postgresql:postgresql
            - tidyup-elasticsearch:elasticsearch
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/tidyUp
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 8080:8080
    tidyup-postgresql:
        extends:
            file: postgresql.yml
            service: tidyup-postgresql
    tidyup-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: tidyup-elasticsearch
